//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolucionOfertas.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class EntitiesOfertas : DbContext
    {
        public EntitiesOfertas()
            : base("name=EntitiesOfertas")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CATEGORIA> CATEGORIA { get; set; }
        public virtual DbSet<COMUNA> COMUNA { get; set; }
        public virtual DbSet<OFERTA> OFERTA { get; set; }
        public virtual DbSet<PERFIL> PERFIL { get; set; }
        public virtual DbSet<PERSONA> PERSONA { get; set; }
        public virtual DbSet<PRODUCTO> PRODUCTO { get; set; }
        public virtual DbSet<PROVINCIA> PROVINCIA { get; set; }
        public virtual DbSet<REGION> REGION { get; set; }
        public virtual DbSet<SUBCATE> SUBCATE { get; set; }
        public virtual DbSet<TIENDA> TIENDA { get; set; }
        public virtual DbSet<EMPRESA> EMPRESA { get; set; }
    
        public virtual int COMUNA_PROCEDURE(string nOMBRE_COMUNA, string iD_PROVINCIA)
        {
            var nOMBRE_COMUNAParameter = nOMBRE_COMUNA != null ?
                new ObjectParameter("NOMBRE_COMUNA", nOMBRE_COMUNA) :
                new ObjectParameter("NOMBRE_COMUNA", typeof(string));
    
            var iD_PROVINCIAParameter = iD_PROVINCIA != null ?
                new ObjectParameter("ID_PROVINCIA", iD_PROVINCIA) :
                new ObjectParameter("ID_PROVINCIA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("COMUNA_PROCEDURE", nOMBRE_COMUNAParameter, iD_PROVINCIAParameter);
        }
    
        public virtual int DIRECCION_PROCEDURE(string cALLE_DIRECCION, Nullable<decimal> nRO_DIRECCION, string dEPTO_DIRECCION, string cOMUNA_ID)
        {
            var cALLE_DIRECCIONParameter = cALLE_DIRECCION != null ?
                new ObjectParameter("CALLE_DIRECCION", cALLE_DIRECCION) :
                new ObjectParameter("CALLE_DIRECCION", typeof(string));
    
            var nRO_DIRECCIONParameter = nRO_DIRECCION.HasValue ?
                new ObjectParameter("NRO_DIRECCION", nRO_DIRECCION) :
                new ObjectParameter("NRO_DIRECCION", typeof(decimal));
    
            var dEPTO_DIRECCIONParameter = dEPTO_DIRECCION != null ?
                new ObjectParameter("DEPTO_DIRECCION", dEPTO_DIRECCION) :
                new ObjectParameter("DEPTO_DIRECCION", typeof(string));
    
            var cOMUNA_IDParameter = cOMUNA_ID != null ?
                new ObjectParameter("COMUNA_ID", cOMUNA_ID) :
                new ObjectParameter("COMUNA_ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DIRECCION_PROCEDURE", cALLE_DIRECCIONParameter, nRO_DIRECCIONParameter, dEPTO_DIRECCIONParameter, cOMUNA_IDParameter);
        }
    
        public virtual int PERFIL_PROCEDURE(string pERFIL_NOMBRE)
        {
            var pERFIL_NOMBREParameter = pERFIL_NOMBRE != null ?
                new ObjectParameter("PERFIL_NOMBRE", pERFIL_NOMBRE) :
                new ObjectParameter("PERFIL_NOMBRE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PERFIL_PROCEDURE", pERFIL_NOMBREParameter);
        }
    
        public virtual int PROVINCIA_PROCEDURE(string nOMBRE_PROVINCIA, string iD_REGION)
        {
            var nOMBRE_PROVINCIAParameter = nOMBRE_PROVINCIA != null ?
                new ObjectParameter("NOMBRE_PROVINCIA", nOMBRE_PROVINCIA) :
                new ObjectParameter("NOMBRE_PROVINCIA", typeof(string));
    
            var iD_REGIONParameter = iD_REGION != null ?
                new ObjectParameter("ID_REGION", iD_REGION) :
                new ObjectParameter("ID_REGION", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROVINCIA_PROCEDURE", nOMBRE_PROVINCIAParameter, iD_REGIONParameter);
        }
    
        public virtual int REGION_PROCEDURE(string nOMBRE_REGION)
        {
            var nOMBRE_REGIONParameter = nOMBRE_REGION != null ?
                new ObjectParameter("NOMBRE_REGION", nOMBRE_REGION) :
                new ObjectParameter("NOMBRE_REGION", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("REGION_PROCEDURE", nOMBRE_REGIONParameter);
        }
    
        public virtual int PERSONA_PROCEDURE(string pERSONA_EMAIL, string pERSONA_RUT, string pERSONA_CONTRASENA, string pERSONA_DV, string pERSONA_NOMBRE, string pERSONA_APELLIDO, string pERSONA_COMUNA)
        {
            var pERSONA_EMAILParameter = pERSONA_EMAIL != null ?
                new ObjectParameter("PERSONA_EMAIL", pERSONA_EMAIL) :
                new ObjectParameter("PERSONA_EMAIL", typeof(string));
    
            var pERSONA_RUTParameter = pERSONA_RUT != null ?
                new ObjectParameter("PERSONA_RUT", pERSONA_RUT) :
                new ObjectParameter("PERSONA_RUT", typeof(string));
    
            var pERSONA_CONTRASENAParameter = pERSONA_CONTRASENA != null ?
                new ObjectParameter("PERSONA_CONTRASENA", pERSONA_CONTRASENA) :
                new ObjectParameter("PERSONA_CONTRASENA", typeof(string));
    
            var pERSONA_DVParameter = pERSONA_DV != null ?
                new ObjectParameter("PERSONA_DV", pERSONA_DV) :
                new ObjectParameter("PERSONA_DV", typeof(string));
    
            var pERSONA_NOMBREParameter = pERSONA_NOMBRE != null ?
                new ObjectParameter("PERSONA_NOMBRE", pERSONA_NOMBRE) :
                new ObjectParameter("PERSONA_NOMBRE", typeof(string));
    
            var pERSONA_APELLIDOParameter = pERSONA_APELLIDO != null ?
                new ObjectParameter("PERSONA_APELLIDO", pERSONA_APELLIDO) :
                new ObjectParameter("PERSONA_APELLIDO", typeof(string));
    
            var pERSONA_COMUNAParameter = pERSONA_COMUNA != null ?
                new ObjectParameter("PERSONA_COMUNA", pERSONA_COMUNA) :
                new ObjectParameter("PERSONA_COMUNA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PERSONA_PROCEDURE", pERSONA_EMAILParameter, pERSONA_RUTParameter, pERSONA_CONTRASENAParameter, pERSONA_DVParameter, pERSONA_NOMBREParameter, pERSONA_APELLIDOParameter, pERSONA_COMUNAParameter);
        }
    
        public virtual int ADD_PRODUCTO_PROCEDURE(string nOMBRE_PRODUCTO, Nullable<decimal> cATEGORIA_PRODUCTO, string dESC_PRODUCTO, Nullable<decimal> pRECIO_PRODUCTO, string iMAGEN_PRODUCTO)
        {
            var nOMBRE_PRODUCTOParameter = nOMBRE_PRODUCTO != null ?
                new ObjectParameter("NOMBRE_PRODUCTO", nOMBRE_PRODUCTO) :
                new ObjectParameter("NOMBRE_PRODUCTO", typeof(string));
    
            var cATEGORIA_PRODUCTOParameter = cATEGORIA_PRODUCTO.HasValue ?
                new ObjectParameter("CATEGORIA_PRODUCTO", cATEGORIA_PRODUCTO) :
                new ObjectParameter("CATEGORIA_PRODUCTO", typeof(decimal));
    
            var dESC_PRODUCTOParameter = dESC_PRODUCTO != null ?
                new ObjectParameter("DESC_PRODUCTO", dESC_PRODUCTO) :
                new ObjectParameter("DESC_PRODUCTO", typeof(string));
    
            var pRECIO_PRODUCTOParameter = pRECIO_PRODUCTO.HasValue ?
                new ObjectParameter("PRECIO_PRODUCTO", pRECIO_PRODUCTO) :
                new ObjectParameter("PRECIO_PRODUCTO", typeof(decimal));
    
            var iMAGEN_PRODUCTOParameter = iMAGEN_PRODUCTO != null ?
                new ObjectParameter("IMAGEN_PRODUCTO", iMAGEN_PRODUCTO) :
                new ObjectParameter("IMAGEN_PRODUCTO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ADD_PRODUCTO_PROCEDURE", nOMBRE_PRODUCTOParameter, cATEGORIA_PRODUCTOParameter, dESC_PRODUCTOParameter, pRECIO_PRODUCTOParameter, iMAGEN_PRODUCTOParameter);
        }
    
        public virtual int CATEGORIA_PROCEDURE(string nOMBRE_CATEGORIA)
        {
            var nOMBRE_CATEGORIAParameter = nOMBRE_CATEGORIA != null ?
                new ObjectParameter("NOMBRE_CATEGORIA", nOMBRE_CATEGORIA) :
                new ObjectParameter("NOMBRE_CATEGORIA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CATEGORIA_PROCEDURE", nOMBRE_CATEGORIAParameter);
        }
    
        public virtual int PERSONA_UPDATE_PROCEDURE(string nOMBRE_PERSONA, string aPELLIDO_PERSONA, string cORREO_PERSONA, string rUT_PERSONA, string iD_DIRECCION, string nUEVA_CALLE)
        {
            var nOMBRE_PERSONAParameter = nOMBRE_PERSONA != null ?
                new ObjectParameter("NOMBRE_PERSONA", nOMBRE_PERSONA) :
                new ObjectParameter("NOMBRE_PERSONA", typeof(string));
    
            var aPELLIDO_PERSONAParameter = aPELLIDO_PERSONA != null ?
                new ObjectParameter("APELLIDO_PERSONA", aPELLIDO_PERSONA) :
                new ObjectParameter("APELLIDO_PERSONA", typeof(string));
    
            var cORREO_PERSONAParameter = cORREO_PERSONA != null ?
                new ObjectParameter("CORREO_PERSONA", cORREO_PERSONA) :
                new ObjectParameter("CORREO_PERSONA", typeof(string));
    
            var rUT_PERSONAParameter = rUT_PERSONA != null ?
                new ObjectParameter("RUT_PERSONA", rUT_PERSONA) :
                new ObjectParameter("RUT_PERSONA", typeof(string));
    
            var iD_DIRECCIONParameter = iD_DIRECCION != null ?
                new ObjectParameter("ID_DIRECCION", iD_DIRECCION) :
                new ObjectParameter("ID_DIRECCION", typeof(string));
    
            var nUEVA_CALLEParameter = nUEVA_CALLE != null ?
                new ObjectParameter("NUEVA_CALLE", nUEVA_CALLE) :
                new ObjectParameter("NUEVA_CALLE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PERSONA_UPDATE_PROCEDURE", nOMBRE_PERSONAParameter, aPELLIDO_PERSONAParameter, cORREO_PERSONAParameter, rUT_PERSONAParameter, iD_DIRECCIONParameter, nUEVA_CALLEParameter);
        }
    
        public virtual int SUBCATE_PROCEDURE(string sUBCATE_NOMBRE, string iD_CATEGORIA)
        {
            var sUBCATE_NOMBREParameter = sUBCATE_NOMBRE != null ?
                new ObjectParameter("SUBCATE_NOMBRE", sUBCATE_NOMBRE) :
                new ObjectParameter("SUBCATE_NOMBRE", typeof(string));
    
            var iD_CATEGORIAParameter = iD_CATEGORIA != null ?
                new ObjectParameter("ID_CATEGORIA", iD_CATEGORIA) :
                new ObjectParameter("ID_CATEGORIA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SUBCATE_PROCEDURE", sUBCATE_NOMBREParameter, iD_CATEGORIAParameter);
        }
    
        public virtual int ADD_EMPRESA_PROCEDURE(string nOMBRE_EMPRESA, string rUT_EMPRESA)
        {
            var nOMBRE_EMPRESAParameter = nOMBRE_EMPRESA != null ?
                new ObjectParameter("NOMBRE_EMPRESA", nOMBRE_EMPRESA) :
                new ObjectParameter("NOMBRE_EMPRESA", typeof(string));
    
            var rUT_EMPRESAParameter = rUT_EMPRESA != null ?
                new ObjectParameter("RUT_EMPRESA", rUT_EMPRESA) :
                new ObjectParameter("RUT_EMPRESA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ADD_EMPRESA_PROCEDURE", nOMBRE_EMPRESAParameter, rUT_EMPRESAParameter);
        }
    
        public virtual int ADD_TIENDA_PROCEDURE(string nOMBRE_TIENDA, string cALLE_TIENDA, Nullable<decimal> nRO_TIENDA, Nullable<decimal> eMPRESA_TIENDA, Nullable<decimal> cOMUNA_TIENDA)
        {
            var nOMBRE_TIENDAParameter = nOMBRE_TIENDA != null ?
                new ObjectParameter("NOMBRE_TIENDA", nOMBRE_TIENDA) :
                new ObjectParameter("NOMBRE_TIENDA", typeof(string));
    
            var cALLE_TIENDAParameter = cALLE_TIENDA != null ?
                new ObjectParameter("CALLE_TIENDA", cALLE_TIENDA) :
                new ObjectParameter("CALLE_TIENDA", typeof(string));
    
            var nRO_TIENDAParameter = nRO_TIENDA.HasValue ?
                new ObjectParameter("NRO_TIENDA", nRO_TIENDA) :
                new ObjectParameter("NRO_TIENDA", typeof(decimal));
    
            var eMPRESA_TIENDAParameter = eMPRESA_TIENDA.HasValue ?
                new ObjectParameter("EMPRESA_TIENDA", eMPRESA_TIENDA) :
                new ObjectParameter("EMPRESA_TIENDA", typeof(decimal));
    
            var cOMUNA_TIENDAParameter = cOMUNA_TIENDA.HasValue ?
                new ObjectParameter("COMUNA_TIENDA", cOMUNA_TIENDA) :
                new ObjectParameter("COMUNA_TIENDA", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ADD_TIENDA_PROCEDURE", nOMBRE_TIENDAParameter, cALLE_TIENDAParameter, nRO_TIENDAParameter, eMPRESA_TIENDAParameter, cOMUNA_TIENDAParameter);
        }
    
        public virtual int ADD_OFERTA_PROCEDURE(string nOMBRE_OFERTA, Nullable<decimal> pRODUCTO_OFERTA, string eSTADO, Nullable<decimal> dSCTO, Nullable<decimal> sTOCK, Nullable<decimal> pRECIO_DESCUENTO)
        {
            var nOMBRE_OFERTAParameter = nOMBRE_OFERTA != null ?
                new ObjectParameter("NOMBRE_OFERTA", nOMBRE_OFERTA) :
                new ObjectParameter("NOMBRE_OFERTA", typeof(string));
    
            var pRODUCTO_OFERTAParameter = pRODUCTO_OFERTA.HasValue ?
                new ObjectParameter("PRODUCTO_OFERTA", pRODUCTO_OFERTA) :
                new ObjectParameter("PRODUCTO_OFERTA", typeof(decimal));
    
            var eSTADOParameter = eSTADO != null ?
                new ObjectParameter("ESTADO", eSTADO) :
                new ObjectParameter("ESTADO", typeof(string));
    
            var dSCTOParameter = dSCTO.HasValue ?
                new ObjectParameter("DSCTO", dSCTO) :
                new ObjectParameter("DSCTO", typeof(decimal));
    
            var sTOCKParameter = sTOCK.HasValue ?
                new ObjectParameter("STOCK", sTOCK) :
                new ObjectParameter("STOCK", typeof(decimal));
    
            var pRECIO_DESCUENTOParameter = pRECIO_DESCUENTO.HasValue ?
                new ObjectParameter("PRECIO_DESCUENTO", pRECIO_DESCUENTO) :
                new ObjectParameter("PRECIO_DESCUENTO", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ADD_OFERTA_PROCEDURE", nOMBRE_OFERTAParameter, pRODUCTO_OFERTAParameter, eSTADOParameter, dSCTOParameter, sTOCKParameter, pRECIO_DESCUENTOParameter);
        }
    
        public virtual int ADD_CATEGORIA_PROCEDURE(string nOMBRE_CATEGORIA)
        {
            var nOMBRE_CATEGORIAParameter = nOMBRE_CATEGORIA != null ?
                new ObjectParameter("NOMBRE_CATEGORIA", nOMBRE_CATEGORIA) :
                new ObjectParameter("NOMBRE_CATEGORIA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ADD_CATEGORIA_PROCEDURE", nOMBRE_CATEGORIAParameter);
        }
    
        public virtual int ADD_COMUNA_PROCEDURE(string nOMBRE_COMUNA, string iD_PROVINCIA)
        {
            var nOMBRE_COMUNAParameter = nOMBRE_COMUNA != null ?
                new ObjectParameter("NOMBRE_COMUNA", nOMBRE_COMUNA) :
                new ObjectParameter("NOMBRE_COMUNA", typeof(string));
    
            var iD_PROVINCIAParameter = iD_PROVINCIA != null ?
                new ObjectParameter("ID_PROVINCIA", iD_PROVINCIA) :
                new ObjectParameter("ID_PROVINCIA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ADD_COMUNA_PROCEDURE", nOMBRE_COMUNAParameter, iD_PROVINCIAParameter);
        }
    
        public virtual int ADD_PERFIL_PROCEDURE(string pERFIL_NOMBRE)
        {
            var pERFIL_NOMBREParameter = pERFIL_NOMBRE != null ?
                new ObjectParameter("PERFIL_NOMBRE", pERFIL_NOMBRE) :
                new ObjectParameter("PERFIL_NOMBRE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ADD_PERFIL_PROCEDURE", pERFIL_NOMBREParameter);
        }
    
        public virtual int ADD_PERSONA_PROCEDURE(string pERSONA_EMAIL, string pERSONA_RUT, string pERSONA_CONTRASENA, string pERSONA_DV, string pERSONA_NOMBRE, string pERSONA_APELLIDO, string pERSONA_COMUNA)
        {
            var pERSONA_EMAILParameter = pERSONA_EMAIL != null ?
                new ObjectParameter("PERSONA_EMAIL", pERSONA_EMAIL) :
                new ObjectParameter("PERSONA_EMAIL", typeof(string));
    
            var pERSONA_RUTParameter = pERSONA_RUT != null ?
                new ObjectParameter("PERSONA_RUT", pERSONA_RUT) :
                new ObjectParameter("PERSONA_RUT", typeof(string));
    
            var pERSONA_CONTRASENAParameter = pERSONA_CONTRASENA != null ?
                new ObjectParameter("PERSONA_CONTRASENA", pERSONA_CONTRASENA) :
                new ObjectParameter("PERSONA_CONTRASENA", typeof(string));
    
            var pERSONA_DVParameter = pERSONA_DV != null ?
                new ObjectParameter("PERSONA_DV", pERSONA_DV) :
                new ObjectParameter("PERSONA_DV", typeof(string));
    
            var pERSONA_NOMBREParameter = pERSONA_NOMBRE != null ?
                new ObjectParameter("PERSONA_NOMBRE", pERSONA_NOMBRE) :
                new ObjectParameter("PERSONA_NOMBRE", typeof(string));
    
            var pERSONA_APELLIDOParameter = pERSONA_APELLIDO != null ?
                new ObjectParameter("PERSONA_APELLIDO", pERSONA_APELLIDO) :
                new ObjectParameter("PERSONA_APELLIDO", typeof(string));
    
            var pERSONA_COMUNAParameter = pERSONA_COMUNA != null ?
                new ObjectParameter("PERSONA_COMUNA", pERSONA_COMUNA) :
                new ObjectParameter("PERSONA_COMUNA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ADD_PERSONA_PROCEDURE", pERSONA_EMAILParameter, pERSONA_RUTParameter, pERSONA_CONTRASENAParameter, pERSONA_DVParameter, pERSONA_NOMBREParameter, pERSONA_APELLIDOParameter, pERSONA_COMUNAParameter);
        }
    
        public virtual int ADD_PROVINCIA_PROCEDURE(string nOMBRE_PROVINCIA, string iD_REGION)
        {
            var nOMBRE_PROVINCIAParameter = nOMBRE_PROVINCIA != null ?
                new ObjectParameter("NOMBRE_PROVINCIA", nOMBRE_PROVINCIA) :
                new ObjectParameter("NOMBRE_PROVINCIA", typeof(string));
    
            var iD_REGIONParameter = iD_REGION != null ?
                new ObjectParameter("ID_REGION", iD_REGION) :
                new ObjectParameter("ID_REGION", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ADD_PROVINCIA_PROCEDURE", nOMBRE_PROVINCIAParameter, iD_REGIONParameter);
        }
    
        public virtual int ADD_REGION_PROCEDURE(string nOMBRE_REGION)
        {
            var nOMBRE_REGIONParameter = nOMBRE_REGION != null ?
                new ObjectParameter("NOMBRE_REGION", nOMBRE_REGION) :
                new ObjectParameter("NOMBRE_REGION", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ADD_REGION_PROCEDURE", nOMBRE_REGIONParameter);
        }
    
        public virtual int ADD_SUBCATE_PROCEDURE(string sUBCATE_NOMBRE, string iD_CATEGORIA)
        {
            var sUBCATE_NOMBREParameter = sUBCATE_NOMBRE != null ?
                new ObjectParameter("SUBCATE_NOMBRE", sUBCATE_NOMBRE) :
                new ObjectParameter("SUBCATE_NOMBRE", typeof(string));
    
            var iD_CATEGORIAParameter = iD_CATEGORIA != null ?
                new ObjectParameter("ID_CATEGORIA", iD_CATEGORIA) :
                new ObjectParameter("ID_CATEGORIA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ADD_SUBCATE_PROCEDURE", sUBCATE_NOMBREParameter, iD_CATEGORIAParameter);
        }
    
        public virtual int UPDATE_PERSONA_PROCEDURE(string nOMBRE_PERSONA, string aPELLIDO_PERSONA, string cORREO_PERSONA, string rUT_PERSONA, string iD_COMUNA)
        {
            var nOMBRE_PERSONAParameter = nOMBRE_PERSONA != null ?
                new ObjectParameter("NOMBRE_PERSONA", nOMBRE_PERSONA) :
                new ObjectParameter("NOMBRE_PERSONA", typeof(string));
    
            var aPELLIDO_PERSONAParameter = aPELLIDO_PERSONA != null ?
                new ObjectParameter("APELLIDO_PERSONA", aPELLIDO_PERSONA) :
                new ObjectParameter("APELLIDO_PERSONA", typeof(string));
    
            var cORREO_PERSONAParameter = cORREO_PERSONA != null ?
                new ObjectParameter("CORREO_PERSONA", cORREO_PERSONA) :
                new ObjectParameter("CORREO_PERSONA", typeof(string));
    
            var rUT_PERSONAParameter = rUT_PERSONA != null ?
                new ObjectParameter("RUT_PERSONA", rUT_PERSONA) :
                new ObjectParameter("RUT_PERSONA", typeof(string));
    
            var iD_COMUNAParameter = iD_COMUNA != null ?
                new ObjectParameter("ID_COMUNA", iD_COMUNA) :
                new ObjectParameter("ID_COMUNA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UPDATE_PERSONA_PROCEDURE", nOMBRE_PERSONAParameter, aPELLIDO_PERSONAParameter, cORREO_PERSONAParameter, rUT_PERSONAParameter, iD_COMUNAParameter);
        }
    }
}
