//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolucionOfertas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERFIL_PERSONA
    {
        public string ID_PERSONA { get; set; }
        public string ID_PERFIL { get; set; }
        public Nullable<decimal> ID { get; set; }
    
        public virtual PERFIL PERFIL { get; set; }
        public virtual PERSONA PERSONA { get; set; }
    }
}
